env:
  es2020: true
extends:
  - eslint:recommended
  - airbnb-typescript
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier
  - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
parserOptions:
  createDefaultProgram: true
  ecmaVersion: 2020
  project: ./tsconfig.json
root: true
