extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - react-app
  - react-app/jest
  - airbnb-typescript
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier
  - prettier/@typescript-eslint
  - prettier/react
parserOptions:
  project: ./tsconfig.json
rules:
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '**/config-overrides.{j,t}s'
        - '**/setupTests.{j,t}s'
        - '**/*.config.{j,t}s'
        - '**/*.{spec,test}.{j,t}{s,sx}'
  react/jsx-filename-extension:
    - error
    - extensions:
        - .jsx
        - .tsx
  react/jsx-uses-react: 'off'
  react/prop-types: 'off'
  react/react-in-jsx-scope: 'off'
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
      path:
        - ./src
