parserOptions:
  project: ./tsconfig.json
rules:
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '**/config-overrides.{j,t}s'
        - '**/setupTests.{j,t}s'
        - '**/*.config.{j,t}s'
        - '**/*.{spec,test}.{j,t}{s,sx}'
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
      path:
        - ./src
